name: Deploy to Azure

on:
  push:
    branches:
      
main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repository
    
uses: actions/checkout@v2

    # Build and push Docker image
    
name: Build and Push Docker image
    uses: docker/build-push-action@v2
    with:
      context: .
      tags: olaewrio0werufeio/fast-api:latest
      push: true# Add other build-push-action parameters if needed

    # Deploy to Azure
    
name: Deploy to Azure
    uses: azure/webapps-deploy@v2
    with:
      app-name: christmas_docker
      slot-name: production  # If you are using deployment slots
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ./